export const COMENZAR_LISTAR_PRODUCTOS = 'COMENZAR_LISTAR_PRODUCTOS'
export const LISTAR_PRODUCTOS_EXITO = 'LISTAR_PRODUCTOS_EXITO'
export const LISTAR_PRODUCTOS_ERROR = 'LISTAR_PRODUCTOS_ERROR'
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO'

export const AGREGAR_PRODUCTO_CARRITO = 'AGREGAR_PRODUCTO_CARRITO'
export const REDUCIR_CANTIDAD_PRODUCTO = 'REDUCIR_CANTIDAD_PRODUCTO'
export const AGREGAR_CANTIDAD_PRODUCTO = 'AGREGAR_CANTIDAD_PRODUCTO'
export const ELIMINAR_PRODUCTO_CARRITO = 'ELIMINAR_PRODUCTO_CARRITO'
